<Project>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
    <PackageVersion>0.1.0-draft</PackageVersion>
    <Version>0.1.0-draft</Version>
    <Authors>gindemit</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile Condition="Exists('README.md')">README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup Condition="Exists('README.md')">
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
