<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GamePlatform.Core/GamePlatform.Core.csproj" />
    <ProjectReference Include="../GamePlatform.Features.Contracts/GamePlatform.Features.Contracts.csproj" />
    <ProjectReference Include="../GamePlatform.Navigation/GamePlatform.Navigation.csproj" />
  </ItemGroup>

</Project>
