#nullable enable
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using GamePlatform.Backend.Contracts.Remote;
using GamePlatform.Core;
using GamePlatform.Features.Accounts;
using GamePlatform.Transport.Abstractions;
using GamePlatform.Transport.Http.Supabase;
namespace GamePlatform.Tests.Transport
{
    public sealed class SupabaseAnonymousAuthLifecycleTests
    {
        static readonly Guid Subject = Guid.Parse("019a1234-1111-7777-8888-999999999999");
        [Fact] public async Task AbsentMarkerIsRecoveryAndSendsNothing() { var x = new Scripted(Response()); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(x, new Store()).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Empty(x.Requests); }
        [Fact] public async Task ExplicitFreshAuthorizationAllowsOneSignupAndPublicMarkerHasNoSecret() { var s = new Store(); var p = P(new Scripted(Response()), s); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.False(await p.AuthorizeFreshAsync(CancellationToken.None)); var r = await p.AuthenticateAsync(CancellationToken.None); Assert.Equal(AccountAuthLifecycleKind.Authenticated, r.Kind); Assert.Equal(SupabaseAnonymousSessionState.Known, s.Current.Public!.State); Assert.DoesNotContain("refresh", s.Current.Public.Subject); Assert.Contains("refresh", Encoding.UTF8.GetString(s.Current.CopySecret()!)); Assert.DoesNotContain("access", Encoding.UTF8.GetString(s.Current.CopySecret()!)); }
        [Fact] public async Task MalformedSignupAndSubjectMismatchAreRecoveryWithoutReplacement() { var malformed = new Store(); var p = P(new Scripted(new HttpResponseData(200, new Dictionary<string, string> { { "Content-Type", "application/json" } }, Encoding.UTF8.GetBytes("{bad"))), malformed); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await p.AuthenticateAsync(CancellationToken.None)).Kind); Assert.Equal(SupabaseAnonymousSessionState.RecoveryRequired, malformed.Current.Public!.State); Assert.Null(malformed.Current.Public.Subject); Assert.Null(malformed.Current.CopySecret()); var known = await Known(); long knownVersion = known.Current.Public!.Version; byte[] originalSecret = known.Current.CopySecret()!; var mismatch = new HttpResponseData(200, new Dictionary<string, string> { { "Content-Type", "application/json" } }, Encoding.UTF8.GetBytes("{\"access_token\":\"a\",\"refresh_token\":\"r\",\"expires_at\":2000,\"user\":{\"id\":\"019a1234-2222-7777-8888-999999999999\"}}")); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(mismatch), known).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Equal(SupabaseAnonymousSessionState.RecoveryRequired, known.Current.Public!.State); Assert.Equal(Subject.ToString("D"), known.Current.Public.Subject); Assert.Equal(knownVersion + 2, known.Current.Public.Version); Assert.Equal(originalSecret, known.Current.CopySecret()); var pending = known.Writes[^2]; Assert.Equal(SupabaseAnonymousSessionState.RefreshPending, pending.Public!.State); Assert.Equal(pending.Public.Version + 1, known.Current.Public.Version); Assert.Equal(pending.Public.Subject, known.Current.Public.Subject); Assert.Equal(pending.CopySecret(), known.Current.CopySecret()); var restart = new Scripted(); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(restart, known).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Empty(restart.Requests); }
        [Fact] public async Task ExpiredSessionRefreshesThroughVersionedRotation() { var store = new Store(); var provider = P(new Scripted(Response("old", "refresh1", 1), Response("new", "refresh2", 3000)), store); Assert.True(await provider.AuthorizeFreshAsync(CancellationToken.None)); var authenticated = await provider.AuthenticateAsync(CancellationToken.None); var token = await authenticated.Session!.GetAsync(CancellationToken.None); Assert.Equal("new", token.Value); Assert.Equal(1, token.Generation); Assert.Contains("refresh2", Encoding.UTF8.GetString(store.Current.CopySecret()!)); }
        [Fact] public async Task UncertainRefreshPersistsRecoveryMarkerAndRestartDoesNotSend() { var store = await Known(); long knownVersion = store.Current.Public!.Version; byte[] originalSecret = store.Current.CopySecret()!; var first = new Scripted(new HttpExecutionException(HttpDeliveryCertainty.Uncertain, "test")); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(first, store).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Single(first.Requests); Assert.Equal(SupabaseAnonymousSessionState.RecoveryRequired, store.Current.Public!.State); Assert.Equal(Subject.ToString("D"), store.Current.Public.Subject); Assert.Equal(knownVersion + 2, store.Current.Public.Version); Assert.Equal(originalSecret, store.Current.CopySecret()); var pending = store.Writes[^2]; Assert.Equal(SupabaseAnonymousSessionState.RefreshPending, pending.Public!.State); Assert.Equal(pending.Public.Version + 1, store.Current.Public.Version); Assert.Equal(pending.Public.Subject, store.Current.Public.Subject); Assert.Equal(pending.CopySecret(), store.Current.CopySecret()); var restart = new Scripted(); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(restart, store).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Empty(restart.Requests); }
        [Fact] public async Task PendingRestartAndKnownMissingSecretAreRecoveryWithoutNewSignup() { var s = new Store(); var p = P(new Scripted(new HttpExecutionException(HttpDeliveryCertainty.Uncertain, "test")), s); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await p.AuthenticateAsync(CancellationToken.None)).Kind); Assert.Equal(SupabaseAnonymousSessionState.RecoveryRequired, s.Current.Public!.State); Assert.Null(s.Current.Public.Subject); Assert.Null(s.Current.CopySecret()); var x = new Scripted(); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(x, s).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Empty(x.Requests); var k = new Store(); await k.Force(SupabaseAnonymousSessionState.Known, Subject.ToString("D"), null); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(), k).AuthenticateAsync(CancellationToken.None)).Kind); }
        [Fact] public async Task NotSentVersionedCleanupRestoresFreshButUncertainDoesNot() { var s = new Store(); var p = P(new Scripted(new HttpExecutionException(HttpDeliveryCertainty.NotSent, "x")), s); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.UnavailableOffline, (await p.AuthenticateAsync(CancellationToken.None)).Kind); Assert.Equal(SupabaseAnonymousSessionState.FreshAuthorized, s.Current.Public!.State); Assert.True(s.Current.Public.Version >= 3); var u = new Store(); var q = P(new Scripted(new HttpExecutionException(HttpDeliveryCertainty.Uncertain, "x")), u); Assert.True(await q.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await q.AuthenticateAsync(CancellationToken.None)).Kind); Assert.Equal(SupabaseAnonymousSessionState.RecoveryRequired, u.Current.Public!.State); }
        [Fact] public async Task SignupNotSentCleanupConflictStoreFailureAndCancellationAreFailClosed() { var conflict = new Store { RejectOnCall = 3 }; var p = P(new Scripted(new HttpExecutionException(HttpDeliveryCertainty.NotSent, "x")), conflict); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await p.AuthenticateAsync(CancellationToken.None)).Kind); var failure = new Store { ThrowOnCall = 3 }; p = P(new Scripted(new HttpExecutionException(HttpDeliveryCertainty.NotSent, "x")), failure); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await p.AuthenticateAsync(CancellationToken.None)).Kind); using var cancelled = new CancellationTokenSource(); var cancellation = new Store { CancelOnCall = 3, Cancellation = cancelled }; p = P(new Scripted(new HttpExecutionException(HttpDeliveryCertainty.NotSent, "x")), cancellation); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); Assert.Equal(AccountAuthLifecycleKind.Cancelled, (await p.AuthenticateAsync(cancelled.Token)).Kind); }
        [Fact] public async Task SessionNotSentCleanupConflictStoreFailureAndCancellationAreFailClosed() { foreach (var mode in new[] { 1, 2 }) { var store = new Store(); var provider = P(new Scripted(Response("old", "refresh1", 1), new HttpExecutionException(HttpDeliveryCertainty.NotSent, "x")), store); Assert.True(await provider.AuthorizeFreshAsync(CancellationToken.None)); var session = (await provider.AuthenticateAsync(CancellationToken.None)).Session!; if (mode == 1) store.RejectOnCall = store.Calls + 2; else store.ThrowOnCall = store.Calls + 2; var error = await Assert.ThrowsAsync<InvalidOperationException>(() => session.GetAsync(CancellationToken.None)); Assert.Contains("recovery", error.Message, StringComparison.OrdinalIgnoreCase); } using var cancelled = new CancellationTokenSource(); var cstore = new Store { Cancellation = cancelled }; var cp = P(new Scripted(Response("old", "refresh1", 1), new HttpExecutionException(HttpDeliveryCertainty.NotSent, "x")), cstore); Assert.True(await cp.AuthorizeFreshAsync(CancellationToken.None)); var cs = (await cp.AuthenticateAsync(CancellationToken.None)).Session!; cstore.CancelOnCall = cstore.Calls + 2; await Assert.ThrowsAnyAsync<OperationCanceledException>(() => cs.GetAsync(cancelled.Token)); }
        [Fact] public async Task RefreshRotatesWinnerAndStoreConflictPublishesNoSession() { var s = await Known(); var gate = new TaskCompletionSource<HttpResponseData>(TaskCreationOptions.RunContinuationsAsynchronously); var firstExecutor = new Scripted(gate.Task); var a = P(firstExecutor, s).AuthenticateAsync(CancellationToken.None); await firstExecutor.FirstSend.Task; var b = await P(new Scripted(Response("bad", "bad")), s).AuthenticateAsync(CancellationToken.None); gate.SetResult(Response("access2", "refresh2")); var ar = await a; Assert.Equal(AccountAuthLifecycleKind.Authenticated, ar.Kind); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, b.Kind); Assert.Contains("refresh2", Encoding.UTF8.GetString(s.Current.CopySecret()!)); var c = await Known(); c.RejectKnown = true; Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(Response("x", "y")), c).AuthenticateAsync(CancellationToken.None)).Kind); }
        [Fact] public async Task CancellationUnavailableOverflowAndNullSnapshotFailClosed() { var s = new Store(); using var c = new CancellationTokenSource(); c.Cancel(); Assert.Equal(AccountAuthLifecycleKind.Cancelled, (await P(new Scripted(), s).AuthenticateAsync(c.Token)).Kind); s.Available = false; Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(), s).AuthenticateAsync(CancellationToken.None)).Kind); var o = new Store(); await o.Force(SupabaseAnonymousSessionState.Known, Subject.ToString("D"), new byte[16385]); Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(), o).AuthenticateAsync(CancellationToken.None)).Kind); o.NullRead = true; Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(), o).AuthenticateAsync(CancellationToken.None)).Kind); }
        [Fact] public async Task InvalidOrOverflowSnapshotAndMalformedStoreSuccessAreRecovery() { Assert.Throws<ArgumentOutOfRangeException>(() => new SupabaseAnonymousSessionSnapshot(new SupabaseAnonymousSessionPublicRecord(0, SupabaseAnonymousSessionState.Known, Subject.ToString("D")), null)); Assert.Throws<ArgumentOutOfRangeException>(() => new SupabaseAnonymousSessionPublicRecord(1, (SupabaseAnonymousSessionState)999, null)); var overflow = new Store { Current = new SupabaseAnonymousSessionSnapshot(new SupabaseAnonymousSessionPublicRecord(long.MaxValue, SupabaseAnonymousSessionState.FreshAuthorized, null), null) }; Assert.Equal(AccountAuthLifecycleKind.RecoveryRequired, (await P(new Scripted(Response()), overflow).AuthenticateAsync(CancellationToken.None)).Kind); Assert.Empty(new Scripted().Requests); var corrupt = new Store { ReturnMaxOnSuccess = true }; var p = P(new Scripted(Response()), corrupt); Assert.False(await p.AuthorizeFreshAsync(CancellationToken.None)); }
        [Fact] public async Task BoundedExecutorRejectsAuthorityRouteRedirectAndOversize() { var cfg = C(1024); var h = new Handler((r, _) => r.RequestUri!.AbsolutePath.EndsWith("signup", StringComparison.Ordinal) ? Task.FromResult(new HttpResponseMessage(HttpStatusCode.Redirect) { RequestMessage = r }) : Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK) { RequestMessage = r, Content = new ByteArrayContent(new byte[1025]) })); using var e = new BoundedSupabaseAuthHttpExecutor(cfg, h); await Assert.ThrowsAsync<HttpExecutionException>(() => e.SendAsync(new HttpRequestData("POST", "https://other.example.test/auth/v1/signup", H(), Encoding.UTF8.GetBytes("{}")), CancellationToken.None)); await Assert.ThrowsAsync<HttpExecutionException>(() => e.SendAsync(new HttpRequestData("POST", cfg.Resolve("bad").AbsoluteUri, H(), Encoding.UTF8.GetBytes("{}")), CancellationToken.None)); await Assert.ThrowsAsync<HttpExecutionException>(() => e.SendAsync(new HttpRequestData("POST", cfg.Resolve("signup").AbsoluteUri, H(), Encoding.UTF8.GetBytes("{}")), CancellationToken.None)); await Assert.ThrowsAsync<HttpExecutionException>(() => e.SendAsync(new HttpRequestData("POST", cfg.Resolve("token?grant_type=refresh_token").AbsoluteUri, H(), Encoding.UTF8.GetBytes("{}")), CancellationToken.None)); }
        static SupabaseAnonymousAuthLifecycle P(IHttpExecutor e, Store s) => new SupabaseAnonymousAuthLifecycle(C(), e, s, new Clock()); static SupabaseAuthConfiguration C(int n = 65536) => new SupabaseAuthConfiguration(new Uri("https://auth.example.test/auth/v1/"), "https://auth.example.test/auth/v1", new BackendNamespace("test"), "public-test", "platform.supabase.session", n); static IReadOnlyDictionary<string, string> H() => new Dictionary<string, string> { { "apikey", "public-test" }, { "Accept", "application/json" }, { "Content-Type", "application/json" } }; static HttpResponseData Response(string a = "access", string r = "refresh", long expires = 2000) => new HttpResponseData(200, new Dictionary<string, string> { { "Content-Type", "application/json" } }, Encoding.UTF8.GetBytes("{\"access_token\":\"" + a + "\",\"refresh_token\":\"" + r + "\",\"expires_at\":" + expires + ",\"user\":{\"id\":\"" + Subject.ToString("D") + "\"}}")); static async Task<Store> Known() { var s = new Store(); var p = P(new Scripted(Response("a", "refresh1")), s); Assert.True(await p.AuthorizeFreshAsync(CancellationToken.None)); await p.AuthenticateAsync(CancellationToken.None); return s; }
        sealed class Clock : IUnixMillisecondClock { public long GetUnixMilliseconds() => 1000000; }
        sealed class Store : ISupabaseAnonymousSessionStore { public bool Available = true, NullRead, RejectKnown, ReturnMaxOnSuccess; public int RejectOnCall, ThrowOnCall, CancelOnCall, Calls; public CancellationTokenSource? Cancellation; public readonly List<SupabaseAnonymousSessionSnapshot> Writes = new List<SupabaseAnonymousSessionSnapshot>(); public SupabaseAnonymousSessionSnapshot Current = SupabaseAnonymousSessionSnapshot.Absent(); public bool IsAvailable => Available; public Task<SupabaseAnonymousSessionSnapshot> ReadAsync(string k, CancellationToken t) => Task.FromResult(NullRead ? null! : Clone(Current)); public Task<SupabaseAnonymousSessionCompareExchangeResult> CompareExchangeAsync(string k, SupabaseAnonymousSessionSnapshot expected, SupabaseAnonymousSessionTransition next, byte[]? secret, CancellationToken t) { var call = Interlocked.Increment(ref Calls); if (call == CancelOnCall) { Cancellation!.Cancel(); return Task.FromCanceled<SupabaseAnonymousSessionCompareExchangeResult>(t); } if (call == ThrowOnCall) throw new InvalidOperationException("store failure"); var match = expected.Exists == Current.Exists && (!expected.Exists || (expected.Public!.Version == Current.Public!.Version && expected.Public.State == Current.Public.State)); if ((RejectKnown && next.State == SupabaseAnonymousSessionState.Known) || call == RejectOnCall) match = false; if (!match) return Task.FromResult(new SupabaseAnonymousSessionCompareExchangeResult(false, Clone(Current))); Current = new SupabaseAnonymousSessionSnapshot(new SupabaseAnonymousSessionPublicRecord(Current.Exists ? Current.Public!.Version + 1 : 1, next.State, next.Subject), secret); Writes.Add(Clone(Current)); var result = ReturnMaxOnSuccess ? new SupabaseAnonymousSessionSnapshot(new SupabaseAnonymousSessionPublicRecord(long.MaxValue, next.State, next.Subject), secret) : Clone(Current); return Task.FromResult(new SupabaseAnonymousSessionCompareExchangeResult(true, result)); } public async Task Force(SupabaseAnonymousSessionState state, string? subject, byte[]? secret) { var e = await ReadAsync("x", CancellationToken.None); await CompareExchangeAsync("x", e, new SupabaseAnonymousSessionTransition(state, subject), secret, CancellationToken.None); } static SupabaseAnonymousSessionSnapshot Clone(SupabaseAnonymousSessionSnapshot v) => new SupabaseAnonymousSessionSnapshot(v.Public == null ? null : new SupabaseAnonymousSessionPublicRecord(v.Public.Version, v.Public.State, v.Public.Subject), v.CopySecret()); }
        sealed class Scripted : IHttpExecutor { readonly Queue<object> q = new Queue<object>(); public List<HttpRequestData> Requests = new List<HttpRequestData>(); public TaskCompletionSource<bool> FirstSend = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously); public Scripted(params object[] x) { foreach (var a in x) q.Enqueue(a); } public async Task<HttpResponseData> SendAsync(HttpRequestData r, CancellationToken t) { Requests.Add(r); FirstSend.TrySetResult(true); if (q.Count == 0) throw new HttpExecutionException(HttpDeliveryCertainty.Uncertain, "test"); var x = q.Dequeue(); if (x is Exception e) throw e; if (x is Task<HttpResponseData> task) return await task.ConfigureAwait(false); return (HttpResponseData)x; } }
        sealed class Handler : HttpMessageHandler { readonly Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> f; public Handler(Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> f) { this.f = f; } protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage r, CancellationToken t) => f(r, t); }
    }
}
