#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using GamePlatform.Core;
using GamePlatform.Storage.Abstractions;
using GamePlatform.Storage.Abstractions.Sync;
using GamePlatform.Storage.Sqlite.Executor;

namespace GamePlatform.Storage.Sqlite.Sync
{
    internal enum SyncCheckpoint { PageStaged, BeforeBootstrapInstall, BootstrapInstalled, BeforePullCommit }

    public sealed class SqlitePrivateSyncStore : IPrivateSyncStore
    {
        private static readonly string[] Required={"profile","progression","inventory","wallet","entitlements"};
        private readonly SqliteDatabase database;private readonly StorageScope scope;private readonly Action<ILocalStorageTransaction> rebuildOverlays;private readonly Action<SyncCheckpoint>? checkpoint;
        public SqlitePrivateSyncStore(SqliteDatabase database,StorageScope scope,Action<ILocalStorageTransaction> rebuildOverlays):this(database,scope,rebuildOverlays,null){}
        internal SqlitePrivateSyncStore(SqliteDatabase database,StorageScope scope,Action<ILocalStorageTransaction> rebuildOverlays,Action<SyncCheckpoint>? checkpoint){this.database=database??throw new ArgumentNullException(nameof(database));this.rebuildOverlays=rebuildOverlays??throw new ArgumentNullException(nameof(rebuildOverlays));this.scope=scope;if(!database.Scope.Equals(scope))throw new StorageException(StorageFailure.InvalidOwner,"The sync scope does not match the database.");this.checkpoint=checkpoint;}

        public Task<BootstrapProgress?> GetBootstrapProgressAsync(CancellationToken token)=>database.ExecuteAsync(scope,t=>{var s=(SqliteTransactionSession)t;if(s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_bootstrap_state WHERE singleton=1")==0)return null;return new BootstrapProgress(new ClientStreamId(Guid.Parse(s.ExecuteScalar<string>("SELECT client_stream_id FROM gp_bootstrap_state WHERE singleton=1"))),s.ExecuteScalar<long>("SELECT committed_through FROM gp_bootstrap_state WHERE singleton=1"),s.ExecuteScalar<long>("SELECT visibility_generation FROM gp_bootstrap_state WHERE singleton=1"),Guid.Parse(s.ExecuteScalar<string>("SELECT log_epoch FROM gp_bootstrap_state WHERE singleton=1")),s.ExecuteScalar<long>("SELECT expires_at FROM gp_bootstrap_state WHERE singleton=1"),s.ExecuteScalar<byte[]>("SELECT session_token FROM gp_bootstrap_state WHERE singleton=1"),s.ExecuteScalar<byte[]>("SELECT next_page_token FROM gp_bootstrap_state WHERE singleton=1"));},token);

        public Task BeginBootstrapAsync(BootstrapBoundary start,CancellationToken token)
        {
            if(start==null)throw new ArgumentNullException(nameof(start));ValidateManifest(start.RequiredCollections);
            return database.ExecuteAsync(scope,t=>{var s=(SqliteTransactionSession)t;EnsureStream(s,start.StreamId);var manifest=string.Join(",",start.RequiredCollections.OrderBy(v=>v,StringComparer.Ordinal));s.Execute("DELETE FROM gp_bootstrap_pages");s.Execute("DELETE FROM gp_bootstrap_entities");s.Execute("DELETE FROM gp_bootstrap_state");s.Execute("INSERT INTO gp_bootstrap_state VALUES (1,?,?,?,?,?,?,?,?)",start.StreamId.ToString(),start.CopySession(),start.CopyFirstPageToken(),start.CommittedThrough,start.VisibilityGeneration,start.LogEpoch.ToString("D"),start.ExpiresAt,manifest);return true;},token);
        }

        public Task StageBootstrapPageAsync(StagedBootstrapPage page,CancellationToken token)
        {
            if(page==null)throw new ArgumentNullException(nameof(page));ValidateMutations(page.Entities,true);
            return database.ExecuteAsync(scope,t=>{var s=(SqliteTransactionSession)t;if(s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_bootstrap_state WHERE singleton=1")!=1)throw new StorageException(StorageFailure.NotReady,"No bootstrap is being staged.");var expectedSession=s.ExecuteScalar<byte[]>("SELECT session_token FROM gp_bootstrap_state WHERE singleton=1");var pageToken=s.ExecuteScalar<byte[]>("SELECT next_page_token FROM gp_bootstrap_state WHERE singleton=1");if(!Equal(expectedSession,page.CopySession())||!Equal(pageToken,page.CopyRequestedPageToken())||page.CommittedThrough!=s.ExecuteScalar<long>("SELECT committed_through FROM gp_bootstrap_state WHERE singleton=1"))throw new StorageException(StorageFailure.IdentityConflict,"The snapshot page is outside the staged boundary.");
                foreach(var entity in page.Entities)UpsertStaged(s,entity);var next=page.CopyNextPageToken();var cursor=page.CopyInitialPullCursor();s.Execute("INSERT INTO gp_bootstrap_pages(page_token,next_page_token,final_cursor) VALUES (?,?,?)",pageToken,next,cursor);checkpoint?.Invoke(SyncCheckpoint.PageStaged);
                if(page.HasMore){s.Execute("UPDATE gp_bootstrap_state SET next_page_token=? WHERE singleton=1",next!);return true;}
                checkpoint?.Invoke(SyncCheckpoint.BeforeBootstrapInstall);Install(s,cursor!);rebuildOverlays(s);checkpoint?.Invoke(SyncCheckpoint.BootstrapInstalled);return true;},token);
        }

        public Task<PullCheckpoint> GetPullCheckpointAsync(CancellationToken token)=>database.ExecuteAsync(scope,t=>{var s=(SqliteTransactionSession)t;if(s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_sync_state WHERE singleton=1 AND ready=1 AND pull_cursor IS NOT NULL")!=1)throw new StorageException(StorageFailure.NotReady,"A complete bootstrap is required before pull.");var fixedCount=s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_sync_state WHERE singleton=1 AND fixed_through IS NOT NULL");return new PullCheckpoint(new ClientStreamId(Guid.Parse(s.ExecuteScalar<string>("SELECT client_stream_id FROM gp_sync_state WHERE singleton=1"))),s.ExecuteScalar<byte[]>("SELECT pull_cursor FROM gp_sync_state WHERE singleton=1"),s.ExecuteScalar<long>("SELECT committed_through FROM gp_sync_state WHERE singleton=1"),fixedCount==0?(long?)null:s.ExecuteScalar<long>("SELECT fixed_through FROM gp_sync_state WHERE singleton=1"));},token);

        public Task ApplyPullPageAsync(StoredPullPage page,CancellationToken token)
        {
            if(page==null)throw new ArgumentNullException(nameof(page));ValidateGroups(page);
            return database.ExecuteAsync(scope,t=>{var s=(SqliteTransactionSession)t;if(s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_sync_state WHERE singleton=1 AND ready=1")!=1)throw new StorageException(StorageFailure.NotReady,"A complete bootstrap is required before pull.");var current=s.ExecuteScalar<long>("SELECT committed_through FROM gp_sync_state WHERE singleton=1");var hasFixed=s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_sync_state WHERE singleton=1 AND fixed_through IS NOT NULL")==1;var fixedThrough=hasFixed?s.ExecuteScalar<long>("SELECT fixed_through FROM gp_sync_state WHERE singleton=1"):page.CommittedThrough;if(fixedThrough!=page.CommittedThrough||page.CommittedThrough<current)throw new StorageException(StorageFailure.IdentityConflict,"The pull page changed its fixed boundary.");foreach(var group in page.Groups)foreach(var change in group.Changes)Apply(s,change);rebuildOverlays(s);checkpoint?.Invoke(SyncCheckpoint.BeforePullCommit);var cursor=page.CopyNextCursor();var applied=page.Groups.Count==0?current:page.Groups[page.Groups.Count-1].Revision;if(!page.HasMore)applied=page.CommittedThrough;s.Execute("UPDATE gp_sync_state SET pull_cursor=?, committed_through=?, fixed_through=? WHERE singleton=1",cursor,applied,page.HasMore?(object)page.CommittedThrough:null!);return true;},token);
        }

        private static void Install(SqliteTransactionSession s,byte[] cursor){s.Execute("DELETE FROM gp_confirmed_projection");s.Execute("INSERT INTO gp_confirmed_projection SELECT collection,entity_key,entity_revision,'visible',payload FROM gp_bootstrap_entities");var stream=s.ExecuteScalar<string>("SELECT client_stream_id FROM gp_bootstrap_state WHERE singleton=1");var through=s.ExecuteScalar<long>("SELECT committed_through FROM gp_bootstrap_state WHERE singleton=1");var visibility=s.ExecuteScalar<long>("SELECT visibility_generation FROM gp_bootstrap_state WHERE singleton=1");var epoch=s.ExecuteScalar<string>("SELECT log_epoch FROM gp_bootstrap_state WHERE singleton=1");s.Execute("DELETE FROM gp_sync_state");s.Execute("INSERT INTO gp_sync_state VALUES (1,?,1,?,?,NULL,?,?)",stream,cursor,through,visibility,epoch);s.Execute("UPDATE gp_stream_state SET ready=1 WHERE singleton=1 AND client_stream_id=?",stream);s.Execute("DELETE FROM gp_bootstrap_pages");s.Execute("DELETE FROM gp_bootstrap_entities");s.Execute("DELETE FROM gp_bootstrap_state");}
        private static void UpsertStaged(SqliteTransactionSession s,StoredProjectionMutation e){if(e.Kind!=StoredProjectionKind.Upsert)throw new StorageException(StorageFailure.Constraint,"Snapshot entities must be upserts.");var count=s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_bootstrap_entities WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey);if(count==0)s.Execute("INSERT INTO gp_bootstrap_entities VALUES (?,?,?,?)",e.Collection,e.EntityKey,e.Revision,e.CopyPayload());else{var revision=s.ExecuteScalar<long>("SELECT entity_revision FROM gp_bootstrap_entities WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey);var payload=s.ExecuteScalar<byte[]>("SELECT payload FROM gp_bootstrap_entities WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey);if(revision!=e.Revision||!Equal(payload,e.CopyPayload()))throw new StorageException(StorageFailure.IdentityConflict,"A staged entity changed within one snapshot.");}}
        private static void Apply(SqliteTransactionSession s,StoredProjectionMutation e){var count=s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_confirmed_projection WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey);if(count!=0){var revision=s.ExecuteScalar<long>("SELECT entity_revision FROM gp_confirmed_projection WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey);if(e.Revision<revision)return;if(e.Revision==revision){var state=s.ExecuteScalar<string>("SELECT state FROM gp_confirmed_projection WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey);var expected=State(e.Kind);var payload=e.CopyPayload();var same=state==expected&&(e.Kind!=StoredProjectionKind.Upsert||Equal(s.ExecuteScalar<byte[]>("SELECT payload FROM gp_confirmed_projection WHERE collection=? AND entity_key=?",e.Collection,e.EntityKey),payload));if(!same)throw new StorageException(StorageFailure.IdentityConflict,"An entity revision changed meaning.");return;}s.Execute("UPDATE gp_confirmed_projection SET entity_revision=?,state=?,payload=? WHERE collection=? AND entity_key=?",e.Revision,State(e.Kind),e.Kind==StoredProjectionKind.Upsert?(object)e.CopyPayload():null!,e.Collection,e.EntityKey);}else s.Execute("INSERT INTO gp_confirmed_projection VALUES (?,?,?,?,?)",e.Collection,e.EntityKey,e.Revision,State(e.Kind),e.Kind==StoredProjectionKind.Upsert?(object)e.CopyPayload():null!);}
        private static string State(StoredProjectionKind kind)=>kind==StoredProjectionKind.Upsert?"visible":kind==StoredProjectionKind.RemoveFromView?"removed":"tombstone";
        private static void EnsureStream(SqliteTransactionSession s,ClientStreamId stream){if(s.ExecuteScalar<int>("SELECT COUNT(*) FROM gp_stream_state WHERE singleton=1 AND client_stream_id=?",stream.ToString())!=1)throw new StorageException(StorageFailure.StreamRecoveryRequired,"The bootstrap stream does not match durable command state.");}
        private static void ValidateManifest(IReadOnlyList<string> values){var seen=new HashSet<string>(StringComparer.Ordinal);foreach(var value in values){if(!Required.Contains(value,StringComparer.Ordinal))throw new StorageException(StorageFailure.Constraint,"An unknown required collection was declared.");if(!seen.Add(value))throw new StorageException(StorageFailure.Constraint,"A collection was declared twice.");}foreach(var required in Required)if(!seen.Contains(required))throw new StorageException(StorageFailure.Constraint,"The bootstrap manifest is incomplete.");}
        private static void ValidateMutations(IReadOnlyList<StoredProjectionMutation> values,bool snapshot){long bytes=0;if(values.Count>1024)throw new StorageException(StorageFailure.Capacity,"A projection page is oversized.");foreach(var value in values){bytes=checked(bytes+value.CopyPayload().Length);if(bytes>262_144)throw new StorageException(StorageFailure.Capacity,"A projection page is oversized.");if(!Required.Contains(value.Collection,StringComparer.Ordinal)||!Enum.IsDefined(typeof(StoredProjectionKind),value.Kind)||(snapshot&&value.Kind!=StoredProjectionKind.Upsert))throw new StorageException(StorageFailure.Constraint,"A required projection kind is unsupported.");}}
        private static void ValidateGroups(StoredPullPage page){long previous=0;foreach(var group in page.Groups){if(group.Revision<=previous||group.Revision>page.CommittedThrough)throw new StorageException(StorageFailure.Constraint,"Pull groups are not complete and ordered.");ValidateMutations(group.Changes,false);previous=group.Revision;}if(page.HasMore&&(page.Groups.Count==0||previous>=page.CommittedThrough))throw new StorageException(StorageFailure.Constraint,"A continuing page made no valid progress.");}
        private static bool Equal(byte[] a,byte[] b){if(a==null||b==null||a.Length!=b.Length)return false;var d=0;for(var i=0;i<a.Length;i++)d|=a[i]^b[i];return d==0;}
    }
}
