// Generated by generate_dtos.py from the reviewed core schema. Do not hand edit.
#nullable enable
using System;
using System.Collections.Generic;

namespace GamePlatform.Wire.Contracts
{
    public interface IProjectionSnapshotEntity { }
    public interface IProjectionChange { }
    public interface IProjectionProfileChangeUnion { }
    public interface IProjectionProgressionChange { }
    public interface IProjectionInventoryChange { }
    public interface IProjectionWalletChange { }
    public interface IProjectionEntitlementChange { }
    public interface IPullResponse { }
    public interface IPushResult { }
    public interface IPushAcceptedResult { }
    public interface IPushPayload { }
    public interface IPushFinalResult { }

    public sealed class AccountResponse
    {
        public AccountResponse(CommonAccount @account, IReadOnlyList<CommonMembership> @memberships, long @serverTime)
        {
            Account = @account ?? throw new ArgumentNullException(nameof(@account));
            Memberships = WireCopy.List(@memberships);
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public CommonAccount Account { get; }
        public IReadOnlyList<CommonMembership> Memberships { get; }
        public long ServerTime { get; }
    }

    public sealed class BootstrapCollection
    {
        public BootstrapCollection(string @name)
        {
            Name = @name ?? throw new ArgumentNullException(nameof(@name));
        }
        public string Name { get; }
        public int SchemaVersion => 1;
        public bool Required => true;
    }

    public sealed class BootstrapStartResponse
    {
        public BootstrapStartResponse(CommonAccount @account, CommonMembership @membership, string @snapshotSession, long @committedThrough, long @visibilityGeneration, Guid @logEpoch, IReadOnlyList<BootstrapCollection> @collections, string @firstPageToken, long @expiresAt, long @serverTime, CommonStreamState @streamState)
        {
            Account = @account ?? throw new ArgumentNullException(nameof(@account));
            Membership = @membership ?? throw new ArgumentNullException(nameof(@membership));
            SnapshotSession = @snapshotSession ?? throw new ArgumentNullException(nameof(@snapshotSession));
            CommittedThrough = @committedThrough;
            VisibilityGeneration = @visibilityGeneration;
            LogEpoch = @logEpoch;
            Collections = WireCopy.List(@collections);
            FirstPageToken = @firstPageToken ?? throw new ArgumentNullException(nameof(@firstPageToken));
            ExpiresAt = @expiresAt;
            ServerTime = @serverTime;
            StreamState = @streamState ?? throw new ArgumentNullException(nameof(@streamState));
        }
        public int ProtocolVersion => 1;
        public CommonAccount Account { get; }
        public CommonMembership Membership { get; }
        public string SnapshotSession { get; }
        public long CommittedThrough { get; }
        public long VisibilityGeneration { get; }
        public Guid LogEpoch { get; }
        public IReadOnlyList<BootstrapCollection> Collections { get; }
        public string FirstPageToken { get; }
        public long ExpiresAt { get; }
        public long ServerTime { get; }
        public CommonStreamState StreamState { get; }
    }

    public sealed class BootstrapPageRequest
    {
        public BootstrapPageRequest(string @snapshotSession, string @pageToken, int @maxBytes)
        {
            SnapshotSession = @snapshotSession ?? throw new ArgumentNullException(nameof(@snapshotSession));
            PageToken = @pageToken ?? throw new ArgumentNullException(nameof(@pageToken));
            MaxBytes = @maxBytes;
        }
        public int ProtocolVersion => 1;
        public string SnapshotSession { get; }
        public string PageToken { get; }
        public int MaxBytes { get; }
    }

    public sealed class BootstrapPageResponse
    {
        public BootstrapPageResponse(string @snapshotSession, long @committedThrough, IReadOnlyList<IProjectionSnapshotEntity> @entities, bool @hasMore, string? @nextPageToken, string? @initialPullCursor, long @serverTime)
        {
            SnapshotSession = @snapshotSession ?? throw new ArgumentNullException(nameof(@snapshotSession));
            CommittedThrough = @committedThrough;
            Entities = WireCopy.List(@entities);
            HasMore = @hasMore;
            NextPageToken = @nextPageToken;
            InitialPullCursor = @initialPullCursor;
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public string SnapshotSession { get; }
        public long CommittedThrough { get; }
        public IReadOnlyList<IProjectionSnapshotEntity> Entities { get; }
        public bool HasMore { get; }
        public string? NextPageToken { get; }
        public string? InitialPullCursor { get; }
        public long ServerTime { get; }
    }

    public sealed class BootstrapStartQuery
    {
        public BootstrapStartQuery(Guid @clientStreamId)
        {
            ClientStreamId = @clientStreamId;
        }
        public Guid ClientStreamId { get; }
    }

    public sealed class CommonError
    {
        public CommonError(string @code, string @category, string @message, bool @retryable, WireOptional<int> @retryAfterMilliseconds, WireOptional<IReadOnlyDictionary<string, ErrorDetailValue>> @details)
        {
            Code = @code ?? throw new ArgumentNullException(nameof(@code));
            Category = @category ?? throw new ArgumentNullException(nameof(@category));
            Message = @message ?? throw new ArgumentNullException(nameof(@message));
            Retryable = @retryable;
            RetryAfterMilliseconds = @retryAfterMilliseconds;
            Details = @details.IsPresent ? WireOptional<IReadOnlyDictionary<string, ErrorDetailValue>>.Present(WireCopy.Map(@details.Value)) : default;
        }
        public string Code { get; }
        public string Category { get; }
        public string Message { get; }
        public bool Retryable { get; }
        public WireOptional<int> RetryAfterMilliseconds { get; }
        public WireOptional<IReadOnlyDictionary<string, ErrorDetailValue>> Details { get; }
    }

    public sealed class CommonExtension
    {
        public CommonExtension(string @schema, int @version, IReadOnlyDictionary<string, ExtensionValue> @value)
        {
            Schema = @schema ?? throw new ArgumentNullException(nameof(@schema));
            Version = @version;
            Value = WireCopy.Map(@value);
        }
        public string Schema { get; }
        public int Version { get; }
        public IReadOnlyDictionary<string, ExtensionValue> Value { get; }
    }

    public sealed class CommonActor
    {
        public CommonActor(string @kind, string @id)
        {
            Kind = @kind ?? throw new ArgumentNullException(nameof(@kind));
            Id = @id ?? throw new ArgumentNullException(nameof(@id));
        }
        public string Kind { get; }
        public string Id { get; }
    }

    public sealed class CommonAccount
    {
        public CommonAccount(Guid @platformUserId, long @createdAt, long @revision)
        {
            PlatformUserId = @platformUserId;
            CreatedAt = @createdAt;
            Revision = @revision;
        }
        public Guid PlatformUserId { get; }
        public long CreatedAt { get; }
        public long Revision { get; }
    }

    public sealed class CommonMembership
    {
        public CommonMembership(Guid @appId, string @status, long @createdAt, long @revision)
        {
            AppId = @appId;
            Status = @status ?? throw new ArgumentNullException(nameof(@status));
            CreatedAt = @createdAt;
            Revision = @revision;
        }
        public Guid AppId { get; }
        public string Status { get; }
        public long CreatedAt { get; }
        public long Revision { get; }
    }

    public sealed class CommonStreamState
    {
        public CommonStreamState(Guid @clientStreamId, Guid @installationId, long @finalizedThrough, long? @nextSequence, string @state)
        {
            ClientStreamId = @clientStreamId;
            InstallationId = @installationId;
            FinalizedThrough = @finalizedThrough;
            NextSequence = @nextSequence;
            State = @state ?? throw new ArgumentNullException(nameof(@state));
        }
        public Guid ClientStreamId { get; }
        public Guid InstallationId { get; }
        public long FinalizedThrough { get; }
        public long? NextSequence { get; }
        public string State { get; }
    }

    public sealed class ErrorResponse
    {
        public ErrorResponse(string @correlationId, CommonError @error, long @serverTime)
        {
            CorrelationId = @correlationId ?? throw new ArgumentNullException(nameof(@correlationId));
            Error = @error ?? throw new ArgumentNullException(nameof(@error));
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public string CorrelationId { get; }
        public CommonError Error { get; }
        public long ServerTime { get; }
    }

    public sealed class GameplayCompletionCommand : IPushPayload
    {
        public GameplayCompletionCommand(string @contentId, int @contentVersion, string @mode, string @difficulty, bool @success, long @score, GameplayValidation @validation, WireOptional<CommonExtension> @extension, string @session, long @durationTicks, int @ticksPerSecond, IReadOnlyDictionary<string, long> @metrics)
        {
            ContentId = @contentId ?? throw new ArgumentNullException(nameof(@contentId));
            ContentVersion = @contentVersion;
            Mode = @mode ?? throw new ArgumentNullException(nameof(@mode));
            Difficulty = @difficulty ?? throw new ArgumentNullException(nameof(@difficulty));
            Success = @success;
            Score = @score;
            Validation = @validation ?? throw new ArgumentNullException(nameof(@validation));
            Extension = @extension;
            Session = @session ?? throw new ArgumentNullException(nameof(@session));
            DurationTicks = @durationTicks;
            TicksPerSecond = @ticksPerSecond;
            Metrics = WireCopy.Map(@metrics);
        }
        public string ContentId { get; }
        public int ContentVersion { get; }
        public string Mode { get; }
        public string Difficulty { get; }
        public bool Success { get; }
        public long Score { get; }
        public GameplayValidation Validation { get; }
        public WireOptional<CommonExtension> Extension { get; }
        public string Session { get; }
        public long DurationTicks { get; }
        public int TicksPerSecond { get; }
        public IReadOnlyDictionary<string, long> Metrics { get; }
    }

    public sealed class ProfileProfile
    {
        public ProfileProfile(string @displayName, WireOptional<string?> @avatarKey, WireOptional<string> @locale, long @revision, long @updatedAt)
        {
            DisplayName = @displayName ?? throw new ArgumentNullException(nameof(@displayName));
            AvatarKey = @avatarKey;
            Locale = @locale;
            Revision = @revision;
            UpdatedAt = @updatedAt;
        }
        public string DisplayName { get; }
        public WireOptional<string?> AvatarKey { get; }
        public WireOptional<string> Locale { get; }
        public long Revision { get; }
        public long UpdatedAt { get; }
    }

    public sealed class ProfileResponse
    {
        public ProfileResponse(ProfileProfile @profile, long @serverTime)
        {
            Profile = @profile ?? throw new ArgumentNullException(nameof(@profile));
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public ProfileProfile Profile { get; }
        public long ServerTime { get; }
    }

    public sealed class ProfilePatchCommand : IPushPayload
    {
        public ProfilePatchCommand(long @expectedRevision, WireOptional<string> @displayName, WireOptional<string?> @avatarKey, WireOptional<string> @locale)
        {
            ExpectedRevision = @expectedRevision;
            DisplayName = @displayName;
            AvatarKey = @avatarKey;
            Locale = @locale;
        }
        public long ExpectedRevision { get; }
        public WireOptional<string> DisplayName { get; }
        public WireOptional<string?> AvatarKey { get; }
        public WireOptional<string> Locale { get; }
    }

    public sealed class ProjectionProfileKey
    {
        public ProjectionProfileKey()
        {
        }
        public string Profile => "self";
    }

    public sealed class ProjectionProgressionKey
    {
        public ProjectionProgressionKey(string @stateKey)
        {
            StateKey = @stateKey ?? throw new ArgumentNullException(nameof(@stateKey));
        }
        public string StateKey { get; }
    }

    public sealed class ProjectionInventoryKey
    {
        public ProjectionInventoryKey(string @itemId)
        {
            ItemId = @itemId ?? throw new ArgumentNullException(nameof(@itemId));
        }
        public string ItemId { get; }
    }

    public sealed class ProjectionWalletKey
    {
        public ProjectionWalletKey(string @currencyId)
        {
            CurrencyId = @currencyId ?? throw new ArgumentNullException(nameof(@currencyId));
        }
        public string CurrencyId { get; }
    }

    public sealed class ProjectionEntitlementKey
    {
        public ProjectionEntitlementKey(string @entitlementId)
        {
            EntitlementId = @entitlementId ?? throw new ArgumentNullException(nameof(@entitlementId));
        }
        public string EntitlementId { get; }
    }

    public sealed class ProjectionProgressionData
    {
        public ProjectionProgressionData(long @value)
        {
            Value = @value;
        }
        public long Value { get; }
    }

    public sealed class ProjectionInventoryData
    {
        public ProjectionInventoryData(long @quantity)
        {
            Quantity = @quantity;
        }
        public long Quantity { get; }
    }

    public sealed class ProjectionWalletData
    {
        public ProjectionWalletData(long @balance)
        {
            Balance = @balance;
        }
        public long Balance { get; }
    }

    public sealed class ProjectionEntitlementData
    {
        public ProjectionEntitlementData(bool @active, long? @expiresAt)
        {
            Active = @active;
            ExpiresAt = @expiresAt;
        }
        public bool Active { get; }
        public long? ExpiresAt { get; }
    }

    public sealed class ProjectionProfileSnapshot : IProjectionSnapshotEntity
    {
        public ProjectionProfileSnapshot(ProjectionProfileKey @entityKey, long @revision, ProfileProfile @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string Collection => "profile";
        public ProjectionProfileKey EntityKey { get; }
        public long Revision { get; }
        public ProfileProfile Data { get; }
    }

    public sealed class ProjectionProgressionSnapshot : IProjectionSnapshotEntity
    {
        public ProjectionProgressionSnapshot(ProjectionProgressionKey @entityKey, long @revision, ProjectionProgressionData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string Collection => "progression";
        public ProjectionProgressionKey EntityKey { get; }
        public long Revision { get; }
        public ProjectionProgressionData Data { get; }
    }

    public sealed class ProjectionInventorySnapshot : IProjectionSnapshotEntity
    {
        public ProjectionInventorySnapshot(ProjectionInventoryKey @entityKey, long @revision, ProjectionInventoryData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string Collection => "inventory";
        public ProjectionInventoryKey EntityKey { get; }
        public long Revision { get; }
        public ProjectionInventoryData Data { get; }
    }

    public sealed class ProjectionWalletSnapshot : IProjectionSnapshotEntity
    {
        public ProjectionWalletSnapshot(ProjectionWalletKey @entityKey, long @revision, ProjectionWalletData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string Collection => "wallet";
        public ProjectionWalletKey EntityKey { get; }
        public long Revision { get; }
        public ProjectionWalletData Data { get; }
    }

    public sealed class ProjectionEntitlementSnapshot : IProjectionSnapshotEntity
    {
        public ProjectionEntitlementSnapshot(ProjectionEntitlementKey @entityKey, long @revision, ProjectionEntitlementData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string Collection => "entitlements";
        public ProjectionEntitlementKey EntityKey { get; }
        public long Revision { get; }
        public ProjectionEntitlementData Data { get; }
    }

    public sealed class ProjectionProfileUpsert : IProjectionChange, IProjectionProfileChangeUnion
    {
        public ProjectionProfileUpsert(ProjectionProfileKey @entityKey, long @revision, ProfileProfile @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string EntityType => "profile";
        public ProjectionProfileKey EntityKey { get; }
        public long Revision { get; }
        public string Kind => "upsert";
        public ProfileProfile Data { get; }
    }

    public sealed class ProjectionProgressionUpsert : IProjectionChange, IProjectionProgressionChange
    {
        public ProjectionProgressionUpsert(ProjectionProgressionKey @entityKey, long @revision, ProjectionProgressionData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string EntityType => "progression";
        public ProjectionProgressionKey EntityKey { get; }
        public long Revision { get; }
        public string Kind => "upsert";
        public ProjectionProgressionData Data { get; }
    }

    public sealed class ProjectionInventoryUpsert : IProjectionChange, IProjectionInventoryChange
    {
        public ProjectionInventoryUpsert(ProjectionInventoryKey @entityKey, long @revision, ProjectionInventoryData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string EntityType => "inventory";
        public ProjectionInventoryKey EntityKey { get; }
        public long Revision { get; }
        public string Kind => "upsert";
        public ProjectionInventoryData Data { get; }
    }

    public sealed class ProjectionWalletUpsert : IProjectionChange, IProjectionWalletChange
    {
        public ProjectionWalletUpsert(ProjectionWalletKey @entityKey, long @revision, ProjectionWalletData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string EntityType => "wallet";
        public ProjectionWalletKey EntityKey { get; }
        public long Revision { get; }
        public string Kind => "upsert";
        public ProjectionWalletData Data { get; }
    }

    public sealed class ProjectionEntitlementUpsert : IProjectionChange, IProjectionEntitlementChange
    {
        public ProjectionEntitlementUpsert(ProjectionEntitlementKey @entityKey, long @revision, ProjectionEntitlementData @data)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Data = @data ?? throw new ArgumentNullException(nameof(@data));
        }
        public string EntityType => "entitlements";
        public ProjectionEntitlementKey EntityKey { get; }
        public long Revision { get; }
        public string Kind => "upsert";
        public ProjectionEntitlementData Data { get; }
    }

    public sealed class ProjectionProfileRemovalValue : IProjectionChange, IProjectionProfileChangeUnion
    {
        public ProjectionProfileRemovalValue(ProjectionProfileKey @entityKey, long @revision, string @kind)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Kind = @kind ?? throw new ArgumentNullException(nameof(@kind));
        }
        public string EntityType => "profile";
        public ProjectionProfileKey EntityKey { get; }
        public long Revision { get; }
        public string Kind { get; }
    }

    public sealed class ProjectionProgressionRemoval : IProjectionChange, IProjectionProgressionChange
    {
        public ProjectionProgressionRemoval(ProjectionProgressionKey @entityKey, long @revision, string @kind)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Kind = @kind ?? throw new ArgumentNullException(nameof(@kind));
        }
        public string EntityType => "progression";
        public ProjectionProgressionKey EntityKey { get; }
        public long Revision { get; }
        public string Kind { get; }
    }

    public sealed class ProjectionInventoryRemoval : IProjectionChange, IProjectionInventoryChange
    {
        public ProjectionInventoryRemoval(ProjectionInventoryKey @entityKey, long @revision, string @kind)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Kind = @kind ?? throw new ArgumentNullException(nameof(@kind));
        }
        public string EntityType => "inventory";
        public ProjectionInventoryKey EntityKey { get; }
        public long Revision { get; }
        public string Kind { get; }
    }

    public sealed class ProjectionWalletRemoval : IProjectionChange, IProjectionWalletChange
    {
        public ProjectionWalletRemoval(ProjectionWalletKey @entityKey, long @revision, string @kind)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Kind = @kind ?? throw new ArgumentNullException(nameof(@kind));
        }
        public string EntityType => "wallet";
        public ProjectionWalletKey EntityKey { get; }
        public long Revision { get; }
        public string Kind { get; }
    }

    public sealed class ProjectionEntitlementRemoval : IProjectionChange, IProjectionEntitlementChange
    {
        public ProjectionEntitlementRemoval(ProjectionEntitlementKey @entityKey, long @revision, string @kind)
        {
            EntityKey = @entityKey ?? throw new ArgumentNullException(nameof(@entityKey));
            Revision = @revision;
            Kind = @kind ?? throw new ArgumentNullException(nameof(@kind));
        }
        public string EntityType => "entitlements";
        public ProjectionEntitlementKey EntityKey { get; }
        public long Revision { get; }
        public string Kind { get; }
    }

    public sealed class ProvisionRequest
    {
        public ProvisionRequest(Guid @installationId, Guid @clientStreamId)
        {
            InstallationId = @installationId;
            ClientStreamId = @clientStreamId;
        }
        public int ProtocolVersion => 1;
        public Guid InstallationId { get; }
        public Guid ClientStreamId { get; }
    }

    public sealed class ProvisionResponse
    {
        public ProvisionResponse(CommonAccount @account, CommonMembership @membership, Guid @clientStreamId, long @nextSequence, long @serverTime)
        {
            Account = @account ?? throw new ArgumentNullException(nameof(@account));
            Membership = @membership ?? throw new ArgumentNullException(nameof(@membership));
            ClientStreamId = @clientStreamId;
            NextSequence = @nextSequence;
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public CommonAccount Account { get; }
        public CommonMembership Membership { get; }
        public Guid ClientStreamId { get; }
        public long NextSequence { get; }
        public long ServerTime { get; }
    }

    public sealed class PullRequest
    {
        public PullRequest(string @cursor, int @maxBytes)
        {
            Cursor = @cursor ?? throw new ArgumentNullException(nameof(@cursor));
            MaxBytes = @maxBytes;
        }
        public int ProtocolVersion => 1;
        public string Cursor { get; }
        public int MaxBytes { get; }
    }

    public sealed class PullGroup
    {
        public PullGroup(long @feedRevision, IReadOnlyList<IProjectionChange> @changes)
        {
            FeedRevision = @feedRevision;
            Changes = WireCopy.List(@changes);
        }
        public long FeedRevision { get; }
        public IReadOnlyList<IProjectionChange> Changes { get; }
    }

    public sealed class PullPage : IPullResponse
    {
        public PullPage(IReadOnlyList<PullGroup> @changes, string @nextCursor, bool @hasMore, long @committedThrough, long @serverTime)
        {
            Changes = WireCopy.List(@changes);
            NextCursor = @nextCursor ?? throw new ArgumentNullException(nameof(@nextCursor));
            HasMore = @hasMore;
            CommittedThrough = @committedThrough;
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public IReadOnlyList<PullGroup> Changes { get; }
        public string NextCursor { get; }
        public bool HasMore { get; }
        public bool ResetRequired => false;
        public long CommittedThrough { get; }
        public long ServerTime { get; }
    }

    public sealed class PullReset : IPullResponse
    {
        public PullReset(IReadOnlyList<IProjectionChange> @changes, string? @nextCursor, string @reason, long @serverTime)
        {
            Changes = WireCopy.List(@changes);
            NextCursor = @nextCursor;
            Reason = @reason ?? throw new ArgumentNullException(nameof(@reason));
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public IReadOnlyList<IProjectionChange> Changes { get; }
        public string? NextCursor { get; }
        public bool HasMore => false;
        public bool ResetRequired => true;
        public string Reason { get; }
        public long ServerTime { get; }
    }

    public sealed class PushOperation
    {
        public PushOperation(Guid @operationId, Guid @installationId, long @sequence, string @type, long @clientCreatedAt, IPushPayload @payload)
        {
            OperationId = @operationId;
            InstallationId = @installationId;
            Sequence = @sequence;
            Type = @type ?? throw new ArgumentNullException(nameof(@type));
            ClientCreatedAt = @clientCreatedAt;
            Payload = @payload ?? throw new ArgumentNullException(nameof(@payload));
        }
        public Guid OperationId { get; }
        public Guid InstallationId { get; }
        public long Sequence { get; }
        public string Type { get; }
        public int SchemaVersion => 1;
        public long ClientCreatedAt { get; }
        public IPushPayload Payload { get; }
    }

    public sealed class PushRequest
    {
        public PushRequest(Guid @clientStreamId, IReadOnlyList<PushOperation> @operations)
        {
            ClientStreamId = @clientStreamId;
            Operations = WireCopy.List(@operations);
        }
        public int ProtocolVersion => 1;
        public Guid ClientStreamId { get; }
        public IReadOnlyList<PushOperation> Operations { get; }
    }

    public sealed class PushAccepted : IPushFinalResult, IPushResult
    {
        public PushAccepted(Guid @operationId, long @sequence, long @feedRevision, IPushAcceptedResult @result)
        {
            OperationId = @operationId;
            Sequence = @sequence;
            FeedRevision = @feedRevision;
            Result = @result ?? throw new ArgumentNullException(nameof(@result));
        }
        public Guid OperationId { get; }
        public long Sequence { get; }
        public string Status => "accepted";
        public long FeedRevision { get; }
        public IPushAcceptedResult Result { get; }
    }

    public sealed class PushTerminalRejected : IPushFinalResult, IPushResult
    {
        public PushTerminalRejected(Guid @operationId, long @sequence, CommonError @error)
        {
            OperationId = @operationId;
            Sequence = @sequence;
            Error = @error ?? throw new ArgumentNullException(nameof(@error));
        }
        public Guid OperationId { get; }
        public long Sequence { get; }
        public string Status => "terminal_rejected";
        public CommonError Error { get; }
    }

    public sealed class PushWaiting : IPushResult
    {
        public PushWaiting(Guid @operationId, long @sequence, long @expectedSequence)
        {
            OperationId = @operationId;
            Sequence = @sequence;
            ExpectedSequence = @expectedSequence;
        }
        public Guid OperationId { get; }
        public long Sequence { get; }
        public string Status => "waiting_for_sequence";
        public long ExpectedSequence { get; }
    }

    public sealed class PushRetryable : IPushResult
    {
        public PushRetryable(Guid @operationId, long @sequence, CommonError @error)
        {
            OperationId = @operationId;
            Sequence = @sequence;
            Error = @error ?? throw new ArgumentNullException(nameof(@error));
        }
        public Guid OperationId { get; }
        public long Sequence { get; }
        public string Status => "retryable";
        public CommonError Error { get; }
    }

    public sealed class PushUpgradeRequired : IPushResult
    {
        public PushUpgradeRequired(Guid @operationId, long @sequence, int @minimumProtocolVersion, CommonError @error)
        {
            OperationId = @operationId;
            Sequence = @sequence;
            MinimumProtocolVersion = @minimumProtocolVersion;
            Error = @error ?? throw new ArgumentNullException(nameof(@error));
        }
        public Guid OperationId { get; }
        public long Sequence { get; }
        public string Status => "upgrade_required";
        public int MinimumProtocolVersion { get; }
        public CommonError Error { get; }
    }

    public sealed class PushResponse
    {
        public PushResponse(Guid @clientStreamId, IReadOnlyList<IPushResult> @operationResults, long @finalizedThrough, long @serverTime)
        {
            ClientStreamId = @clientStreamId;
            OperationResults = WireCopy.List(@operationResults);
            FinalizedThrough = @finalizedThrough;
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public Guid ClientStreamId { get; }
        public IReadOnlyList<IPushResult> OperationResults { get; }
        public long FinalizedThrough { get; }
        public long ServerTime { get; }
    }

    public sealed class RecoveryReceiptRequest
    {
        public RecoveryReceiptRequest(Guid @clientStreamId, Guid @operationId, Guid @installationId, long @sequence, string @fingerprint)
        {
            ClientStreamId = @clientStreamId;
            OperationId = @operationId;
            InstallationId = @installationId;
            Sequence = @sequence;
            Fingerprint = @fingerprint ?? throw new ArgumentNullException(nameof(@fingerprint));
        }
        public int ProtocolVersion => 1;
        public Guid ClientStreamId { get; }
        public Guid OperationId { get; }
        public Guid InstallationId { get; }
        public long Sequence { get; }
        public string Fingerprint { get; }
    }

    public sealed class RecoveryReceiptResponse
    {
        public RecoveryReceiptResponse(Guid @clientStreamId, bool @found, IPushFinalResult? @result, long @serverTime, Guid @operationId, long @observedFinalizedThrough)
        {
            ClientStreamId = @clientStreamId;
            Found = @found;
            Result = @result;
            ServerTime = @serverTime;
            OperationId = @operationId;
            ObservedFinalizedThrough = @observedFinalizedThrough;
        }
        public int ProtocolVersion => 1;
        public Guid ClientStreamId { get; }
        public bool Found { get; }
        public IPushFinalResult? Result { get; }
        public long ServerTime { get; }
        public Guid OperationId { get; }
        public long ObservedFinalizedThrough { get; }
    }

    public sealed class RecoveryStreamRequest
    {
        public RecoveryStreamRequest(Guid @installationId, Guid @priorClientStreamId, Guid @newClientStreamId, string @reason, Guid @recoveryId, string @inspectionToken, long @expectedFinalizedThrough)
        {
            InstallationId = @installationId;
            PriorClientStreamId = @priorClientStreamId;
            NewClientStreamId = @newClientStreamId;
            Reason = @reason ?? throw new ArgumentNullException(nameof(@reason));
            RecoveryId = @recoveryId;
            InspectionToken = @inspectionToken ?? throw new ArgumentNullException(nameof(@inspectionToken));
            ExpectedFinalizedThrough = @expectedFinalizedThrough;
        }
        public int ProtocolVersion => 1;
        public Guid InstallationId { get; }
        public Guid PriorClientStreamId { get; }
        public Guid NewClientStreamId { get; }
        public string Reason { get; }
        public Guid RecoveryId { get; }
        public string InspectionToken { get; }
        public long ExpectedFinalizedThrough { get; }
    }

    public sealed class RecoveryStreamResponse
    {
        public RecoveryStreamResponse(Guid @priorClientStreamId, Guid @newClientStreamId, long @nextSequence, long @priorFinalizedThrough, long @serverTime, Guid @recoveryId)
        {
            PriorClientStreamId = @priorClientStreamId;
            NewClientStreamId = @newClientStreamId;
            NextSequence = @nextSequence;
            PriorFinalizedThrough = @priorFinalizedThrough;
            ServerTime = @serverTime;
            RecoveryId = @recoveryId;
        }
        public int ProtocolVersion => 1;
        public Guid PriorClientStreamId { get; }
        public Guid NewClientStreamId { get; }
        public long NextSequence { get; }
        public long PriorFinalizedThrough { get; }
        public long ServerTime { get; }
        public Guid RecoveryId { get; }
    }

    public sealed class RecoveryInspectRequest
    {
        public RecoveryInspectRequest(Guid @clientStreamId, Guid @installationId)
        {
            ClientStreamId = @clientStreamId;
            InstallationId = @installationId;
        }
        public int ProtocolVersion => 1;
        public Guid ClientStreamId { get; }
        public Guid InstallationId { get; }
    }

    public sealed class RecoveryInspectResponse
    {
        public RecoveryInspectResponse(CommonStreamState @streamState, string @inspectionToken, long @expiresAt, long @serverTime)
        {
            StreamState = @streamState ?? throw new ArgumentNullException(nameof(@streamState));
            InspectionToken = @inspectionToken ?? throw new ArgumentNullException(nameof(@inspectionToken));
            ExpiresAt = @expiresAt;
            ServerTime = @serverTime;
        }
        public int ProtocolVersion => 1;
        public CommonStreamState StreamState { get; }
        public string InspectionToken { get; }
        public long ExpiresAt { get; }
        public long ServerTime { get; }
    }

    public sealed class PushProfileUpdatedResult : IPushAcceptedResult
    {
        public PushProfileUpdatedResult(long @profileRevision)
        {
            ProfileRevision = @profileRevision;
        }
        public string Kind => "profile_updated";
        public long ProfileRevision { get; }
    }

    public sealed class PushGameplayCompletionRecordedResult : IPushAcceptedResult
    {
        public PushGameplayCompletionRecordedResult()
        {
        }
        public string Kind => "gameplay_completion_recorded";
        public bool CompletionRecorded => true;
    }

    public sealed class GameplayValidation
    {
        public GameplayValidation(string @scheme, string @reference)
        {
            Scheme = @scheme ?? throw new ArgumentNullException(nameof(@scheme));
            Reference = @reference ?? throw new ArgumentNullException(nameof(@reference));
        }
        public string Scheme { get; }
        public string Reference { get; }
    }
}
