"""Generate attribute-free carriers from the exact reviewed schema mirror.

Validation remains the codec boundary's responsibility: these carriers preserve
wire presence and types without silently normalizing consumer identifiers.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
schemas = {p.name: json.loads(p.read_text()) for p in sorted((ROOT / 'contracts/v1/schemas').glob('*.json'))}
nodes = {}
for file, schema in schemas.items():
    for name, value in schema['$defs'].items():
        nodes[(file, name)] = value

def pascal(value):
    return value[0].upper() + value[1:]

def cname(key):
    return pascal(key[0].split('.')[0]) + pascal(key[1])

def refkey(ref, file):
    filepart, fragment = ref.split('#/$defs/')
    return (filepart or file, fragment)

def deref(key):
    while '$ref' in nodes[key]:
        key = refkey(nodes[key]['$ref'], key[0])
    return key

# Give inline objects/unions stable names, with no serializer metadata on DTOs.
nodes[('push.schema.json', 'profileUpdatedResult')] = nodes[('push.schema.json', 'accepted')]['properties']['result']['oneOf'][0]
nodes[('push.schema.json', 'gameplayCompletionRecordedResult')] = nodes[('push.schema.json', 'accepted')]['properties']['result']['oneOf'][1]
nodes[('push.schema.json', 'acceptedResult')] = {'oneOf': [{'$ref': '#/$defs/profileUpdatedResult'}, {'$ref': '#/$defs/gameplayCompletionRecordedResult'}]}
nodes[('push.schema.json', 'accepted')]['properties']['result'] = {'$ref': '#/$defs/acceptedResult'}
nodes[('gameplay.schema.json', 'validation')] = nodes[('gameplay.schema.json', 'completionCommand')]['properties']['validation']
nodes[('gameplay.schema.json', 'completionCommand')]['properties']['validation'] = {'$ref': '#/$defs/validation'}
nodes[('push.schema.json', 'payload')] = {'oneOf': [{'$ref': 'profile.schema.json#/$defs/patchCommand'}, {'$ref': 'gameplay.schema.json#/$defs/completionCommand'}]}
nodes[('push.schema.json', 'operation')]['properties']['payload'] = {'$ref': '#/$defs/payload'}
nodes[('push.schema.json', 'finalResult')] = {'oneOf': [{'$ref': '#/$defs/accepted'}, {'$ref': '#/$defs/terminalRejected'}]}
nodes[('recovery.schema.json', 'receiptResponse')]['properties']['result'] = {'oneOf': [{'$ref': 'push.schema.json#/$defs/finalResult'}, {'type': 'null'}]}

def union(key):
    node = nodes[key]
    return 'oneOf' in node and all('$ref' in x for x in node['oneOf'])

unions = [key for key in nodes if union(key)]
objects = [key for key, value in nodes.items() if value.get('type') == 'object' and 'properties' in value]
bases = {key: [] for key in objects}

def leaves(key):
    key = deref(key)
    if union(key):
        return [leaf for branch in nodes[key]['oneOf'] for leaf in leaves(refkey(branch['$ref'], key[0]))]
    return [key]

for key in unions:
    for leaf in leaves(key):
        if leaf in bases: bases[leaf].append('I' + cname(key))

def typename(node, file, field=''):
    if '$ref' in node:
        key = deref(refkey(node['$ref'], file))
        if key in objects: return cname(key)
        if key in unions: return 'I' + cname(key)
        if key[1] in ('uuid', 'uuidV7'): return 'Guid'
        if key[1] in ('nonNegativeInt64', 'positiveInt64', 'signedInt64', 'timestamp'): return 'long'
        return typename(nodes[key], key[0], field)
    if 'oneOf' in node:
        valid = [x for x in node['oneOf'] if x.get('type') != 'null']
        if len(valid) == 1: return typename(valid[0], file, field) + '?'
        raise ValueError((file, field, node))
    if 'const' in node:
        v = node['const']
        return 'bool' if isinstance(v, bool) else ('int' if isinstance(v, int) else 'string')
    typ = node.get('type')
    if typ == 'string' or 'enum' in node: return 'string'
    if typ == 'integer': return 'int'
    if typ == 'boolean': return 'bool'
    if typ == 'null': return 'string?'
    if typ == 'array': return 'IReadOnlyList<' + (typename(node['items'], file, field) if 'items' in node else 'IProjectionChange') + '>'
    if typ == 'object':
        value = 'ExtensionValue' if 'x-recursiveScalars' in node else ('ErrorDetailValue' if field == 'details' else typename(node['additionalProperties'], file))
        return 'IReadOnlyDictionary<string, ' + value + '>'
    raise ValueError((file, field, node))

def literal(value):
    if value is True: return 'true'
    if value is False: return 'false'
    return json.dumps(value, ensure_ascii=True)

lines = ['// Generated by generate_dtos.py from the reviewed core schema. Do not hand edit.', '#nullable enable', 'using System;', 'using System.Collections.Generic;', '', 'namespace GamePlatform.Wire.Contracts', '{']
catalog = []
for key in unions:
    lines.append('    public interface I' + cname(key) + ' { }')

for key in objects:
    node = nodes[key]
    name = cname(key)
    props = []
    for field, schema in node['properties'].items():
        typ = typename(schema, key[0], field)
        optional = field not in node.get('required', [])
        constant = 'const' in schema and '$ref' not in schema
        # Protocol version is fixed in the referenced scalar definition.
        if schema.get('$ref', '').endswith('/protocolVersion'):
            constant, schema = True, {'const': 1}
        if optional: typ = 'WireOptional<' + typ + '>'
        props.append({'wire': field, 'property': pascal(field), 'parameter': '@' + field, 'type': typ, 'optional': optional, 'constant': constant, 'schema': schema})
    lines.append('')
    lines.append('    public sealed class ' + name + (' : ' + ', '.join(sorted(set(bases[key]))) if bases[key] else ''))
    lines.append('    {')
    params = [p for p in props if not p['constant']]
    lines.append('        public ' + name + '(' + ', '.join(p['type'] + ' ' + p['parameter'] for p in params) + ')')
    lines.append('        {')
    for p in params:
        expr = p['parameter']
        typ = p['type']
        if typ.startswith('IReadOnlyList<'): expr = 'WireCopy.List(' + expr + ')'
        elif typ.startswith('IReadOnlyDictionary<'): expr = 'WireCopy.Map(' + expr + ')'
        elif typ.startswith('WireOptional<IReadOnlyDictionary<'):
            inner = typ[len('WireOptional<'):-1]
            expr = expr + '.IsPresent ? WireOptional<' + inner + '>.Present(WireCopy.Map(' + expr + '.Value)) : default'
        elif not typ.startswith('WireOptional<') and not typ.endswith('?') and typ not in ('Guid','long','int','bool'):
            expr += ' ?? throw new ArgumentNullException(nameof(' + p['parameter'] + '))'
        lines.append('            ' + p['property'] + ' = ' + expr + ';')
    lines.append('        }')
    for p in props:
        suffix = ' => ' + literal(p['schema']['const']) + ';' if p['constant'] else ' { get; }'
        lines.append('        public ' + p['type'] + ' ' + p['property'] + suffix)
    lines.append('    }')
    source = key[0] + '#/$defs/' + key[1]
    source = {
        'push.schema.json#/$defs/profileUpdatedResult': 'push.schema.json#/$defs/accepted/properties/result/oneOf/0',
        'push.schema.json#/$defs/gameplayCompletionRecordedResult': 'push.schema.json#/$defs/accepted/properties/result/oneOf/1',
        'gameplay.schema.json#/$defs/validation': 'gameplay.schema.json#/$defs/completionCommand/properties/validation',
    }.get(source, source)
    catalog.append({'schema': key[0] + '#/$defs/' + key[1], 'sourceSchema': source, 'type': name, 'interfaces': sorted(set(bases[key])), 'properties': props})
lines.append('}')
(OUT / 'CoreDtos.g.cs').write_text('\n'.join(lines) + '\n')
(OUT / 'dto-catalog.json').write_text(json.dumps({'canonicalCommit': '0109936f0ebf232924cec70adb79c4f790b604bc', 'objects': catalog,
    'unions': [{'type': 'I' + cname(key), 'schema': key[0] + '#/$defs/' + key[1], 'branches': [cname(leaf) for leaf in leaves(key)]} for key in unions],
    'aliases': {key[0] + '#/$defs/' + key[1]: typename(nodes[key], key[0]) for key in nodes if '$ref' in nodes[key]}}, indent=2) + '\n')
print(f'Generated {len(objects)} immutable DTO classes and {len(unions)} union interfaces.')
