"""Generate the P3 schema-checkpoint carriers without enabling a runtime codec."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
CONTRACTS = ROOT / "contracts"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


snapshot = json.loads((CONTRACTS / "snapshot.json").read_text(encoding="utf-8"))
if snapshot.get("contractVersion") != "0.4.0-g3-schema-checkpoint.1":
    raise SystemExit("G3 schema checkpoint mirror is not active")
for relative in (
    "g3/client-mappings.json",
    "g3/reward-receipt.schema.json",
    "live-slice/receipt.schema.json",
):
    if digest(CONTRACTS / relative) != snapshot["files"].get(relative):
        raise SystemExit(f"Contract pin mismatch: {relative}")

mappings = json.loads((CONTRACTS / "g3/client-mappings.json").read_text(encoding="utf-8"))
expected_types = [
    "G3RewardReceiptRequest",
    "G3RewardReceiptNotFoundResponse",
    "G3RewardReceiptCompletionResponse",
    "LiveSliceRewardReceipt",
]
if [entry["csharp"] for entry in mappings["mappings"]] != expected_types:
    raise SystemExit("Reviewed G3 C# mappings changed")

source = '''// Generated by generate_g3_dtos.py from 0.4.0-g3-schema-checkpoint.1. Do not hand edit.
#nullable enable
using System;
using System.Collections.Generic;

namespace GamePlatform.Wire.Contracts
{
    public interface IG3RewardReceiptResponse { }
    public interface ILiveSliceRewardLine { }

    public sealed class G3RewardReceiptRequest
    {
        public G3RewardReceiptRequest(Guid operationId) { OperationId = operationId; }
        public Guid OperationId { get; }
    }

    public sealed class G3RewardReceiptNotFoundResponse : IG3RewardReceiptResponse
    {
        public G3RewardReceiptNotFoundResponse(Guid operationId) { OperationId = operationId; }
        public int ProtocolVersion => 1;
        public int SchemaVersion => 2;
        public Guid OperationId { get; }
        public string Status => "not_found";
    }

    public sealed class G3RewardReceiptCompletionResponse : IG3RewardReceiptResponse
    {
        public G3RewardReceiptCompletionResponse(Guid operationId, LiveSliceRewardReceipt? reward)
        {
            OperationId = operationId;
            Reward = reward;
        }
        public int ProtocolVersion => 1;
        public int SchemaVersion => 2;
        public Guid OperationId { get; }
        public string Status => "completion_recorded";
        public string OutcomeAuthority => "client_trusted_unvalidated";
        public LiveSliceRewardReceipt? Reward { get; }
    }

    public sealed class LiveSliceRewardSource
    {
        public LiveSliceRewardSource(string key, string rewardSlot, string policyId, int policyVersion)
        {
            Key = key ?? throw new ArgumentNullException(nameof(key));
            RewardSlot = rewardSlot ?? throw new ArgumentNullException(nameof(rewardSlot));
            PolicyId = policyId ?? throw new ArgumentNullException(nameof(policyId));
            PolicyVersion = policyVersion;
        }
        public string Kind => "gameplay.completion";
        public string Key { get; }
        public string RewardSlot { get; }
        public string PolicyId { get; }
        public int PolicyVersion { get; }
    }

    public sealed class LiveSliceRewardReceipt
    {
        public LiveSliceRewardReceipt(Guid grantId, Guid originatingOperationId, long feedRevision,
            long recordedAt, LiveSliceRewardSource source, string planId, int planVersion,
            IReadOnlyList<ILiveSliceRewardLine> lines)
        {
            GrantId = grantId;
            OriginatingOperationId = originatingOperationId;
            FeedRevision = feedRevision;
            RecordedAt = recordedAt;
            Source = source ?? throw new ArgumentNullException(nameof(source));
            PlanId = planId ?? throw new ArgumentNullException(nameof(planId));
            PlanVersion = planVersion;
            Lines = WireCopy.List(lines);
        }
        public Guid GrantId { get; }
        public Guid OriginatingOperationId { get; }
        public long FeedRevision { get; }
        public long RecordedAt { get; }
        public LiveSliceRewardSource Source { get; }
        public string PlanId { get; }
        public int PlanVersion { get; }
        public IReadOnlyList<ILiveSliceRewardLine> Lines { get; }
    }

    public sealed class LiveSliceCurrencyRewardLine : ILiveSliceRewardLine
    {
        public LiveSliceCurrencyRewardLine(int lineIndex, int definitionVersion, string currencyId, long quantity)
        {
            LineIndex = lineIndex;
            DefinitionVersion = definitionVersion;
            CurrencyId = currencyId ?? throw new ArgumentNullException(nameof(currencyId));
            Quantity = quantity;
        }
        public int LineIndex { get; }
        public int DefinitionVersion { get; }
        public string Kind => "currency";
        public string CurrencyId { get; }
        public long Quantity { get; }
    }

    public sealed class LiveSliceStackRewardLine : ILiveSliceRewardLine
    {
        public LiveSliceStackRewardLine(int lineIndex, int definitionVersion, string itemId, long quantity)
        {
            LineIndex = lineIndex;
            DefinitionVersion = definitionVersion;
            ItemId = itemId ?? throw new ArgumentNullException(nameof(itemId));
            Quantity = quantity;
        }
        public int LineIndex { get; }
        public int DefinitionVersion { get; }
        public string Kind => "item_stack";
        public string ItemId { get; }
        public long Quantity { get; }
    }

    public sealed class LiveSliceEntitlementRewardLine : ILiveSliceRewardLine
    {
        public LiveSliceEntitlementRewardLine(int lineIndex, int definitionVersion,
            string entitlementId, long? expiresAt)
        {
            LineIndex = lineIndex;
            DefinitionVersion = definitionVersion;
            EntitlementId = entitlementId ?? throw new ArgumentNullException(nameof(entitlementId));
            ExpiresAt = expiresAt;
        }
        public int LineIndex { get; }
        public int DefinitionVersion { get; }
        public string Kind => "entitlement";
        public string EntitlementId { get; }
        public long? ExpiresAt { get; }
    }
}
'''

catalog = {
    "canonicalCommit": "0518ad565efdfe16df13e78e2acbb92033e8bd30",
    "contractVersion": snapshot["contractVersion"],
    "codecStatus": "unimplemented_unverified",
    "types": [
        {"type": "G3RewardReceiptRequest", "schema": "g3/reward-receipt.schema.json#/$defs/request"},
        {"type": "IG3RewardReceiptResponse", "schema": "g3/reward-receipt.schema.json#/$defs/response",
         "branches": ["G3RewardReceiptNotFoundResponse", "G3RewardReceiptCompletionResponse"]},
        {"type": "LiveSliceRewardReceipt", "schema": "live-slice/receipt.schema.json#/$defs/receipt"},
        {"type": "ILiveSliceRewardLine", "schema": "live-slice/receipt.schema.json#/$defs/receipt/properties/lines/items",
         "branches": ["LiveSliceCurrencyRewardLine", "LiveSliceStackRewardLine", "LiveSliceEntitlementRewardLine"]},
    ],
    "presence": {
        "completion.reward": "required nullable; C# nullable property, never WireOptional",
        "not_found.reward": "absent and forbidden",
        "completion.outcomeAuthority": "required constant client_trusted_unvalidated",
    },
    "reusedCore": mappings["reusedCore"],
}
catalog_text = json.dumps(catalog, indent=2) + "\n"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
targets = {
    OUT / "G3CheckpointDtos.g.cs": source,
    OUT / "g3-dto-catalog.json": catalog_text,
}
if args.check:
    for path, expected in targets.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"Generated G3 DTO artifact drift: {path.name}")
else:
    for path, value in targets.items():
        path.write_text(value, encoding="utf-8", newline="\n")
    print("Generated 8 G3 schema-checkpoint carrier classes and 2 union interfaces; runtime codec remains unimplemented.")
