<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GamePlatform.Core/GamePlatform.Core.csproj" />
    <ProjectReference Include="../GamePlatform.Backend.Contracts/GamePlatform.Backend.Contracts.csproj" />
    <ProjectReference Include="../GamePlatform.Transport.Abstractions/GamePlatform.Transport.Abstractions.csproj" />
    <ProjectReference Include="../GamePlatform.Wire.Contracts/GamePlatform.Wire.Contracts.csproj" />
    <ProjectReference Include="../GamePlatform.Serialization.MessagePack/GamePlatform.Serialization.MessagePack.csproj" />
  </ItemGroup>

</Project>
